"""empty message

Revision ID: d57eef6b35b4
Revises: 2cc4e4a49273
Create Date: 2020-07-04 17:07:27.793443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57eef6b35b4'
down_revision = '2cc4e4a49273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'property', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'owner_id')
    # ### end Alembic commands ###
